export interface Publication {
    venue: string;
    venueFull: string;
    title: string;
    authors: string;
    /** Where the PDF or record lives, and what to call it in the citation. */
    source: { label: string; href: string };
    /**
     * First page of the paper, in public/covers. Optional — a publication
     * whose PDF cannot be fetched drops the column rather than showing a
     * placeholder, which is why HAL has none: it sits behind a bot challenge.
     *
     * Regenerated by hand rather than in CI, so the build stays hermetic and
     * needs no poppler:
     *
     *   curl -sL -o p.pdf <pdf-url>
     *   pdftoppm -png -r 90 -f 1 -l 1 p.pdf p
     *   python3 -c "from PIL import Image; im=Image.open('p-01.png'); \
     *     im.thumbnail((320,460)); im.save('public/covers/<name>.webp','WEBP',quality=82)"
     */
    cover?: string;
}

/** Newest first. */
export const publications: Publication[] = [
    {
        venue: "LAC 2026",
        venueFull: "Linux Audio Conference",
        title: "SeamLess: Distributed Spatial Audio Rendering on the Linux Audio Stack",
        authors: "Fares Schulz, Max Weidauer, Stefan Weinzierl, Henrik von Coler",
        source: { label: "HAL", href: "https://hal.science/hal-05697686/document" }
    },
    {
        venue: "DAFx 2025",
        venueFull: "28th Int. Conf. on Digital Audio Effects",
        title: "Pitch-Conditioned Instrument Sound Synthesis From an Interactive Timbre Latent Space",
        authors: "Christian Limberg, Fares Schulz, Zhe Zhang, Stefan Weinzierl",
        source: { label: "arXiv", href: "https://arxiv.org/abs/2510.04339" },
        cover: "/covers/pitch-conditioned.webp"
    },
    {
        venue: "IS² 2024",
        venueFull: "5th IEEE Int. Symposium on the Internet of Sounds",
        title: "anira: An Architecture for Neural Network Inference in Real-Time Audio Applications",
        authors: "Valentin Ackva, Fares Schulz",
        source: { label: "arXiv", href: "https://arxiv.org/abs/2506.12665" },
        cover: "/covers/anira.webp"
    }
];
