export interface Publication {
    /** Where and when it was accepted, phrased for the citation line. */
    venue: string;
    title: string;
    authors: string;
    /**
     * One or two sentences in plain language: what the work is and what it
     * does. Written from the paper's own abstract — a title alone tells a
     * visitor who is not in the field nothing at all.
     */
    summary: string;
    /** Where to read it, and anything else worth linking. */
    links: { label: string; href: string }[];
    /**
     * First page of the paper, in public/covers. Optional — a publication with
     * no cover keeps an empty slot rather than showing a placeholder, so the
     * columns stay level.
     *
     * Regenerated by hand rather than in CI, so the build stays hermetic and
     * needs no poppler. Note that HAL prepends its own cover sheet, so a paper
     * fetched from there wants page 2 rather than page 1:
     *
     *   pdftoppm -png -r 90 -f 1 -l 1 paper.pdf out
     *   python3 -c "from PIL import Image; im=Image.open('out-1.png'); \
     *     im.thumbnail((320,460)); im.save('public/covers/<name>.webp','WEBP',quality=82)"
     */
    cover?: string;
}

/** Newest first. */
export const publications: Publication[] = [
    {
        venue: "Accepted to Linux Audio Conference 2026",
        title: "SeamLess: Distributed Spatial Audio Rendering on the Linux Audio Stack",
        authors: "Fares Schulz, Max Weidauer, Stefan Weinzierl, Henrik von Coler",
        summary:
            "A modular real-time renderer that spreads spatial audio processing across several Linux servers, so Ambisonics and Wave Field Synthesis can drive hundreds of loudspeakers — past what a single machine can carry.",
        links: [
            { label: "Read on HAL", href: "https://hal.science/hal-05697686" },
            // SeamLess is a system of components spread across the tu-studio
            // org rather than one repository, so the documentation site is the
            // honest entry point — it is what links the parts together.
            { label: "Documentation", href: "https://tu-studio.github.io/seamless-docs/" }
        ],
        cover: "/covers/seamless.webp"
    },
    {
        venue: "Accepted to DAFx 2025 — Int. Conf. on Digital Audio Effects",
        title: "Pitch-Conditioned Instrument Sound Synthesis From an Interactive Timbre Latent Space",
        authors: "Christian Limberg, Fares Schulz, Zhe Zhang, Stefan Weinzierl",
        summary:
            "A two-stage model that disentangles pitch from timbre, so instrument sounds can be steered through a small, navigable latent space rather than the high-dimensional one such systems usually leave you with.",
        links: [
            { label: "Read on arXiv", href: "https://arxiv.org/abs/2510.04339" },
            { label: "Listen", href: "https://pgesam.faresschulz.com/" },
            { label: "GitHub", href: "https://github.com/faressc/pgesam" }
        ],
        cover: "/covers/pitch-conditioned.webp"
    },
    {
        venue: "Accepted to IS² 2024 — IEEE Int. Symposium on the Internet of Sounds",
        title: "anira: An Architecture for Neural Network Inference in Real-Time Audio Applications",
        authors: "Valentin Ackva, Fares Schulz",
        summary:
            "A cross-platform C++ library that moves neural inference off the audio callback and onto a static thread pool, with ONNX Runtime, LibTorch and TensorFlow Lite behind one interface.",
        links: [
            { label: "Read on arXiv", href: "https://arxiv.org/abs/2506.12665" },
            { label: "GitHub", href: "https://github.com/anira-project/anira" }
        ],
        cover: "/covers/anira.webp"
    }
];
